/// Chapter stub generated by `flux new`.
document {
  meta {
    version = "0.3.0";
  }
  body {
    section chapter2 {
      text heading { style = "H2"; content = "Chapter 2"; }
      text body { content = "Edit this chapter file."; }
    }
  }
}
