/// Chapter fragment generated by `flux new`.
/// This file is included by the main document.
document {
  meta {
    version = "0.3.0";
  }
  body {
    section chapter2 {
      text heading { style = "H2"; content = "Chapter 2"; }
      text body { content = "Edit this chapter fragment to build the section."; }
      callout chapterNote {
        tone = "note";
        text noteBody { content = "Keep chapter sections modular and focused."; }
      }
    }
  }
}
